### ISSUE TITLE
Container tag

### ISSUE THREAD

**Issue by pkrog** [phnmnl/phenomenal-h2020#3]
@phnmnl/core-devel 
Currently, the tag of a container in Jenkins is set to:
`v${TOOL_VERSION}_cv${CONTAINER_VERSION}.${BUILD_NUMBER}`
Where
 - `TOOL_VERSION` is the version of the tool.
 - `CONTAINER_VERSION` is the container version in the form `x.y` where x and y are integers.
 - `BUILD_NUMBER` is an integer.
An example would be : `v5.4_cv1.5.6`, where `BUILD_NUMBER=6`.

`BUILD_NUMBER`, which is handled and increased automatically by Jenkins, is used as the patch number (`z` part of version number `x.y.z`) of the container version. `CONTAINER_VERSION`, on the other hand, must be set to `x.y`.
This means a developer must not handle by himself the `z` part. When you a slight change (a patch) in your container code, you don't have to increase the version number, Jenkins will handle it for you. On the other if you do a minor change (`y` part), then you have to increase the version number.

We assume that the patch number (`z`) is the same as the Jenkins build number, considering that all builds should be triggered by new commits in github. However, a change in comments or a forced rebuild in Jenkins will lead as well to an increase of the build number. This could later be misinterpreted as a patch.

A second solution, would be to let developers of containers handle themselves the patch number (i.e. the whole `x.y.z` version number of their container) and add the Jenkins build number at the end of the tag, using  `_b` as a separator.
`v${TOOL_VERSION}_cv${CONTAINER_VERSION}_b.${BUILD_NUMBER}`
With the same example as above we would have: `v5.4_cv1.5_b6` or `v5.4_cv1.5.4_b6` if the developer decides to you a patch number for his container.

What would you consider to be the best solution between both ?
Do you have another suggestion ?
Please, start a conversation here, so we can decide what seems best.

**Comment by pcm32** [comment]
I would prefer the scheme where build number is assigned to patch (x.y.z is major.minor.patch) automatically. So that means, staying as we are. My reasoning is the following:

- As developer, I'm happier if I need to decide only on incrementing two numbers (major and minor) instead of deciding on incrementing three numbers (major, minor and patch). Besides, having to manage the patch increment manually, a decision needs to be made too often in my opinion (every time you push actually you'll need to decide whether you change the patch number somewhere), and this is a pain.
- While is true that not all triggered builds in jenkins will be due to a commit, in our setting with hooks looking at the git repos, most of them should be due to commits/pushes and I would expect only a tiny amount of them to be due to manual triggers. I cannot think at least of any other automatic number increment besides the build that so closely mimicks commit/pushes in our setting.
- Because of the previous two points, I would say I'm willing to pay the cost of having a few build numbers produced by manual builds if that means that I don't need to worry about incrementing the patch number every time I do a commit/push.
- In terms of aesthetics, I think that the version of a container `v5.4_cv1.5.6` is already long to make it even longer to `v5.4_cv1.5.6_b57`.
- In my experience, setting version numbers is hard, and most developers (me included) will probably avoid/forget changing the patch number as often as they should. I think that it would lead to a less tidy versioning pattern.

**Comment by michaelvanvliet** [comment]
I like the automated numbering by using the Jenkins build no. in the version. All, either manual or automatic, builds should result in a new patch/version. I think by keeping minor changes in a feature branch we can prevent Jenkins from re-building insignificant changes. My feeling is that we should try to simplify and automate the software building, testing and releasing as much as possible.

**Comment by pcm32** [comment]
Can we close this @pierrickrogermele ?
