### ISSUE TITLE
Galaxy outside kubernetes doc

### ISSUE THREAD

**Issue by jbradbury** [phnmnl/phenomenal-h2020#40]
Instillation and settup for galaxy section talks about features that will be included as of v16.07. What part of this tutorial can now be deleted?

https://github.com/phnmnl/phenomenal-h2020/wiki/Galaxy-outside-Kubernetes

**Comment by sneumann** [comment]
Hi, I edited that page https://github.com/phnmnl/phenomenal-h2020/wiki/Galaxy-outside-Kubernetes/_compare/2cfdf5db423564605b3919687d30880a42db52a7...f850d6299ccc0933415c2ec501d512835612640f
to include the information from https://github.com/galaxyproject/galaxy/blob/051bc950731365b580d3569be8c0481f8bcecf86/config/job_conf.xml.sample_advanced#L121
This does not use https://github.com/pcm32/pykube/tree/feature/allMergedFeatures anymore. 
Since current Phnmnl is based on the production Galaxy >16.07, this should be safe, but I can't guarantee that.
